= Grails Shiro plugin
:icons: font
:iconfont-cdn: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css
:stylesdir: resources/style/
:stylesheet: asciidoctor.css
:description: Grails shiro plugin
:keywords: documentation, Grails, Shiro, 3.3.10, 1.4.1
:links:
:numbered:
:sectlinks:

This is the Grails Shiro plugin for grails version 3.3.x and Shiro 1.4.1. This was derived from the Grails 2.x version
(https://github.com/pledbrook/grails-shiro).

We pretty much re-wrote the plugin for Grails 3 and to simplify the use, improve the documentation and make it easier to
maintain. There are lots of changes please check out the
https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc[Guide] in the docs directory.

== Installation

To install add this to your `build.gradle` dependencies:

 compile "org.grails.plugins:grails-shiro:3.0"

== Getting started

If you're implementing your security from scratch, then you can simply install grails-shiro by adding
`compile "org.grails.plugins:grails-shiro:3.0"` to your build.gradle dependencies and typing
shiro quick start, https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc#shiro-quick-start['grails shiro-quick-start'].

This will create a ShiroWildcardDbRealm in your `grails-app/realms` directory and make a ShiroUser and ShiroRole domain
class. It will also create an AuthController to let you log in. Check out
https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc#wildcard-db-realm[Wildcard DB Realm] for how you might populate
a couple of users using Boostrap.groovy.

Now to Control access to a Controller add an Interceptor for that controller using
`https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc#create-shiro-controller-interceptor[grails create-shiro-controller-interceptor] MyController` which will add
https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc#permission-string-conventions[access control by convention].

== Building from source

To build the plugin yourself and install it from this repo:

1. clone or fork this repo to your machine
2. run `gradle install` and that will build, test, install it to your local maven repo (~/.m2)
3. profit!

== Kudos

* https://github.com/pledbrook/grails-shiro/commits?author=pledbrook[Peter Ledbrook] looking after original grails shiro plugin
* https://github.com/pledbrook/grails-shiro/commits?author=yellowsnow[yellowsnow]
* https://github.com/pledbrook/grails-shiro/commits?author=apandichi[apandichi]
* and https://github.com/pledbrook/grails-shiro/graphs/contributors[others] for work on the previous version of the plugin.