= Grails Shiro plugin
:icons: font
:iconfont-cdn: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css
:stylesdir: docs/resources/style/
:stylesheet: asciidoctor.css
:description: Grails shiro plugin
:keywords: documentation, Grails, Shiro, 3.3.10, 4.0.0, 1.4.1
:links:
:sectlinks:
:toc: left
:toclevels: 2
:toc-class: toc2


image:https://travis-ci.org/nerdErg/grails-shiro.svg?branch=master["Build Status", link="https://travis-ci.org/nerdErg/grails-shiro"]

== Versions

* Latest released versions 3.2, 4.2
* Latest working version 4.3

This is the Grails Shiro plugin for grails version 4.0.x and Shiro 1.5.3. This was derived from the Grails 2.x version
(https://github.com/pledbrook/grails-shiro).

We pretty much re-wrote the plugin for Grails 3 and to simplify the use, improve the documentation and make it easier to
maintain. There are lots of changes please check out the
https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc[Guide] in the docs directory.

=== Numbering

In general the version number is following the Grails major version it supports, then release. e.g.

 3.2 = Grails 3 plugin release 2
 4.3 = Grails 4 plugin release 3

=== Maintenance
Although we have now published the Grails 4 version of this plugin we will continue to maintain the Grails 3 version
backporting features till July 2020 where possible.

=== Documentation and Source

In general the documentation applies to both Grails 3 and 4 versions of the plugin. Source code including specific documentation
for the Grails 3 version can be found in the Grails-3 Branch.

== Installation

To install, add this to your `build.gradle` dependencies for Grails 4:

 compile "org.grails.plugins:grails-shiro:4.3"

and this for Grails 3:

 compile "org.grails.plugins:grails-shiro:3.2"

== Getting started

If you're implementing your security from scratch, then you can simply install grails-shiro by adding
`compile "org.grails.plugins:grails-shiro:4.3"` to your build.gradle dependencies and typing
shiro quick start, https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc#shiro-quick-start['grails shiro-quick-start'].

This will create a ShiroWildcardDbRealm in your `grails-app/realms` directory and make a ShiroUser and ShiroRole domain
class. It will also create an AuthController to let you log in. Check out
https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc#wildcard-db-realm[Wildcard DB Realm] for how you might populate
a couple of users using Boostrap.groovy.

Now to Control access to a Controller add an Interceptor for that controller using
`https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc#create-shiro-controller-interceptor[grails create-shiro-controller-interceptor] MyController` which will add
https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc#permission-string-conventions[access control by convention].

== Version change log

=== version 4.3

* Fixed Annotation redirect missing context path - https://github.com/nerdErg/grails-shiro/issues/16
* Upgrade to shiro 1.5.3

WARNING: This introduces a small breaking change. Annotations now use the login and unauthorized settings not URL Mappings
to set where they redirect to.

=== version 4.2

* upgrade to shiro 1.4.2

=== version 4.1

* ported to Grails version 4.0.0 (thanks Peter Legen/animator013 for you help!)

=== version 3.1

* Added ability to set the remember me cipherKey or the length of the randomly generated key
* Fix for onNotAuthenticated and onUnauthorized not working correctly (https://github.com/nerdErg/grails-shiro/pull/6[Can't be invoked on metaclass])

=== version 3.0

* re-write from old Grails 2 plugin see updates in the https://github.com/nerdErg/grails-shiro/blob/master/docs/Guide.adoc[Guide]

== Building from source

To build the plugin yourself and install it from this repo:

1. clone or fork this repo to your machine
2. run `gradle install` and that will build, test, install it to your local maven repo (~/.m2)
3. profit!

== Kudos

* https://github.com/pledbrook/grails-shiro/commits?author=pledbrook[Peter Ledbrook] looking after original grails shiro plugin
* https://github.com/pledbrook/grails-shiro/commits?author=yellowsnow[yellowsnow]
* https://github.com/pledbrook/grails-shiro/commits?author=apandichi[apandichi]
* https://github.com/animator013[animator013 - Peter Legen]
* and https://github.com/pledbrook/grails-shiro/graphs/contributors[others] for work on the previous version of the plugin.

Thank you to everyone who provides feedback!