package com.nerderg

/**
 * Generated by the Shiro plugin. This interceptor class protects all URLs
 * via access control by convention.
 */
class NotAuthenticatedInterceptor {

    int order = HIGHEST_PRECEDENCE + 100

    NotAuthenticatedInterceptor() {
        match(controller: 'notAuthenticated').excludes(action: 'publicAction')
    }

    boolean onNotAuthenticated(subject, interceptor) {
        return interceptor.render("override")
    }

    boolean before() {
        accessControl()
    }

    void afterView() {
    }
}