package ${packageName}

/**
 * Generated by the Shiro plugin. This interceptor class allows access to the ${className}
 * without being authenticated, so you can login etc.
 */
class ${className} {

    //customize me
    int order = HIGHEST_PRECEDENCE+100

    boolean before() { true }
    boolean after() { true }
}
